#  Copyright 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---

#Configure build and deploy kubeflow v1.0

- name: Download kfctl v1.0.2 release from the Kubeflow releases page.
  unarchive:
    src: https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_linux.tar.gz
    dest: /usr/bin/
    remote_src: yes
    mode: 0755

- name: Delete Omnia Kubeflow Directory if exists
  file:
    path: /root/k8s/omnia-kubeflow
    state: absent

- name: Create Kubeflow Directory
  file:
    path: /root/k8s/omnia-kubeflow
    mode: 0755
    state: directory
    recurse: yes

- name: Build Kubeflow Configuration
  command:
    cmd: /usr/bin/kfctl build -V -f https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml
    chdir: /root/k8s/omnia-kubeflow

- name: Modify Cpu Limit for istio-ingressgateway-service-account
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/istio-install/base/istio-noauth.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: '---'
    regexp: 'cpu: 100m'
    replace: 'cpu: 2'

- name: Modify Mem Limit for istio-ingressgateway-service-account
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/istio-install/base/istio-noauth.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: '---'
    regexp: 'memory: 128Mi'
    replace: 'memory: 512Mi'

- name: Modify Cpu Request for istio-ingressgateway-service-account
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/istio-install/base/istio-noauth.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: '---'
    regexp: 'cpu: 10m'
    replace: 'cpu: 1'

- name: Modify Mem Request for istio-ingressgateway-service-account
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/istio-install/base/istio-noauth.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: '---'
    regexp: 'memory: 40Mi'
    replace: 'memory: 256Mi'


- name: Modify Cpu Limit for kfserving-gateway
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/kfserving-gateway/base/deployment.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: 'env:'
    regexp: 'cpu: 100m'
    replace: 'cpu: 2'

- name: Modify Mem Limit for kfserving-gateway
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/kfserving-gateway/base/deployment.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: 'env:'
    regexp: 'memory: 128Mi'
    replace: 'memory: 512Mi'

- name: Modify Cpu Request for kfserving-gateway
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/kfserving-gateway/base/deployment.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: 'env:'
    regexp: 'cpu: 10m'
    replace: 'cpu: 1'

- name: Modify Mem Request for kfserving-gateway
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/kfserving-gateway/base/deployment.yaml
    after: 'serviceAccountName: istio-ingressgateway-service-account'
    before: 'env:'
    regexp: 'memory: 40Mi'
    replace: 'memory: 256Mi'


- name: Change Argo base service from NodePort to LoadBalancer
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/argo/base/service.yaml
    regexp: 'NodePort'
    replace: 'LoadBalancer'

- name: Change istio-install base istio-noauth service from NodePort to LoadBalancer
  replace:
    path: /root/k8s/omnia-kubeflow/kustomize/istio-install/base/istio-noauth.yaml
    regexp: 'NodePort'
    replace: 'LoadBalancer'

- name: Apply Kubeflow Configuration
  command:
    cmd: /usr/bin/kfctl apply -V -f /root/k8s/omnia-kubeflow/kfctl_k8s_istio.v1.0.2.yaml
    chdir: /root/k8s/omnia-kubeflow
