---

#- name: Enable docker service
  #service:
    #name: docker
    #enabled: yes
#
- name: Start and Enable docker service
  service:
    name: docker
    state: restarted
    enabled: yes
  #tags: install

- name: Start and Enable Kubernetes - kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
  #tags: install

